Repository PaackEng/paack-ui, pull requests merged in 2020-08, with the labels that each got.

#70 WMS-440 | Adapt Table componet to allow selecting multiple rows
  showcase/src/Checkboxes/Stories.elm
  showcase/src/Tables/Book.elm
  showcase/src/Tables/Model.elm
  showcase/src/Tables/Msg.elm
  showcase/src/Tables/Stories.elm
  src/UI/Badge.elm
  src/UI/Checkbox.elm
  src/UI/Internal/Tables/FiltersView.elm
  src/UI/Internal/Tables/View.elm
  src/UI/Tables/Stateful.elm
  src/UI/Tables/Stateless.elm
  src/UI/Utils/ARIA.elm
Labels: design-sync, enhancement

#73 WMS-415 | Ellipsize table cell content
  showcase/src/Tables/Book.elm
  src/UI/Internal/EllipsizableTooltip.elm
  src/UI/Internal/Tables/Common.elm
  src/UI/Internal/Tables/FiltersView.elm
  src/UI/Internal/Tables/View.elm
  src/UI/Internal/Text.elm
  src/UI/Internal/Utils/Element.elm
  src/UI/Tables/Common.elm
  src/UI/Utils/Element.elm
Labels: enhancement

#74 WMS-441 | Add Tabs component
  elm.json
  showcase/src/Main.elm
  showcase/src/Model.elm
  showcase/src/Msg.elm
  showcase/src/Tabs/Model.elm
  showcase/src/Tabs/Msg.elm
  showcase/src/Tabs/Stories.elm
  src/UI/Tables/Common.elm
  src/UI/Tabs.elm
  src/UI/Utils/ARIA.elm
  tests/Tests/UI/Tabs.elm
Labels: design-sync, enhancement

#75 Bump node-elm-compiler; Add Tabs to cypress
  cypress/integration/visual-regression.spec.js
  yarn.lock
Labels: enhancement

#82 WMS-462 | Cleanup/Analyse Showcase
  elm.json
  package.json
  showcase/src/Alerts.elm
  showcase/src/Badges.elm
  showcase/src/Buttons/Stories.elm
  showcase/src/Checkboxes/Stories.elm
  showcase/src/Icons.elm
  showcase/src/LoadingView.elm
  showcase/src/Main.elm
  showcase/src/Paginators/Stories.elm
  showcase/src/Palette.elm
  showcase/src/Radio/Stories.elm
  showcase/src/Sizes.elm
  showcase/src/Tables/Book.elm
  showcase/src/Tables/Stories.elm
  showcase/src/Tabs/Model.elm
  showcase/src/Tabs/Stories.elm
  showcase/src/TextField.elm
  showcase/src/Texts.elm
  showcase/src/Utils.elm
Labels: cleanup, enhancement

#83 WMS-508 | Fix Package-page's Table on Mobile
  src/UI/Internal/Text.elm
Labels: bug

#84 WMS-472 | Update icons
  showcase/src/Icons.elm
  src/UI/Button.elm
  src/UI/Icon.elm
  src/UI/Internal/Dialog.elm
  src/UI/Internal/SideBar.elm
Labels: blocked by paack-ui-assets

#85 WMS-500 | WMS-484 | Part one of changes required to Group Views
  src/UI/ListView.elm
  src/UI/Utils/Element.elm
  tests/Tests/UI/ListView.elm
Labels: enhancement
