Repository PaackEng/paack-ui, pull requests merged in 2020-07, with the labels that each got.

#50 WMS-315 | Phase 3 filtered-sortable table (Table v3) - part 1
  elm.json
  showcase/src/Tables/Model.elm
  showcase/src/Tables/Msg.elm
  showcase/src/Tables/Stories.elm
  src/UI/Badge.elm
  src/UI/Button.elm
  src/UI/Internal/Basics.elm
  src/UI/Internal/Dialog.elm
  src/UI/Internal/Filters.elm
  src/UI/Internal/FiltersHeaders.elm
  src/UI/Internal/NArray.elm
  src/UI/Internal/NList.elm
  src/UI/Internal/Palette.elm
  src/UI/Internal/Primitives.elm
  src/UI/Internal/SideBar.elm
  src/UI/Internal/Table.elm
  src/UI/Internal/TableView.elm
  src/UI/Internal/TypeNumbers.elm
  src/UI/Table.elm
  src/UI/Tables/Common.elm
  src/UI/Tables/Stateful.elm
  src/UI/Tables/Stateless.elm
  src/UI/TextField.elm
  src/UI/Utils/Element.elm
  src/UI/Utils/TypeNumbers.elm
Labels: design-sync, enhancement

#51 WMS-315 | Table Filters
  elm.json
  showcase/elm.json
  showcase/src/Main.elm
  showcase/src/Sizes.elm
  showcase/src/Tables/Model.elm
  showcase/src/Tables/Stories.elm
  src/UI/Checkbox.elm
  src/UI/Internal/DateInput.elm
  src/UI/Internal/Filters.elm
  src/UI/Internal/FiltersHeaders.elm
  src/UI/Internal/NArray.elm
  src/UI/Internal/Primitives.elm
  src/UI/RadioButton.elm
  src/UI/Tables/Stateful.elm
  src/UI/TextField.elm
Labels: design-sync, enhancement

#53 WMS-315 | Update Checkbox and RadioButton to match Figma
  package.json
  showcase/src/Checkboxes/Model.elm
  showcase/src/Checkboxes/Msg.elm
  showcase/src/Checkboxes/Stories.elm
  showcase/src/Main.elm
  showcase/src/Model.elm
  showcase/src/Msg.elm
  showcase/src/Radio/Model.elm
  showcase/src/Radio/Msg.elm
  showcase/src/Radio/Stories.elm
  showcase/src/Tables/Stories.elm
  src/UI/Checkbox.elm
  src/UI/Icon.elm
  src/UI/Internal/DateInput.elm
  src/UI/Internal/Filters.elm
  src/UI/Internal/FiltersHeaders.elm
  src/UI/Internal/TableView.elm
  src/UI/Radio.elm
  src/UI/RadioButton.elm
  src/UI/Tables/Stateful.elm
  src/UI/Utils/ARIA.elm
  yarn.lock
Labels: design-sync, enhancement

#54 WMS-315 | Update table docs
  elm.json
  src/UI/Checkbox.elm
  src/UI/Icon.elm
  src/UI/ListView.elm
  src/UI/NavigationContainer.elm
  src/UI/Radio.elm
  src/UI/Tables/Common.elm
  src/UI/Tables/Stateful.elm
  src/UI/Tables/Stateless.elm
  src/UI/TextField.elm
  src/UI/Utils/ARIA.elm
  src/UI/Utils/Element.elm
  src/UI/Utils/TypeNumbers.elm
Labels: documentation

#56 [README] Add showcase
  README.md
  showcase/README.md
Labels: documentation

#58 Figma Sync
  showcase/src/LoadingView.elm
  showcase/src/Utils.elm
  src/UI/Checkbox.elm
  src/UI/Internal/Dialog.elm
  src/UI/Internal/Tables/Common.elm
  src/UI/Internal/Tables/Filters.elm
  src/UI/Internal/Tables/FiltersView.elm
  src/UI/Internal/Tables/View.elm
  src/UI/Radio.elm
  src/UI/Tables/Common.elm
  src/UI/Tables/Stateful.elm
  src/UI/Tables/Stateless.elm
Labels: design-sync

#60 WMS-404 | Fix ToggleButton theme
  showcase/src/Buttons/Stories.elm
  src/UI/Button.elm
Labels: bug

#64 WMS-395 | Adjust pagination to use small sized buttons
  src/UI/Paginator.elm
Labels: design-sync, enhancement

#63 WMS-401 | Add hovering and click on entire radio's row
  showcase/src/Radio/Stories.elm
  src/UI/Internal/Tables/FiltersView.elm
  src/UI/Radio.elm
Labels: design-sync, enhancement

#62 WMS-399 | Fix ellipsis behaviour
  src/UI/Internal/Text.elm
  src/UI/Internal/Utils/Element.elm
  src/UI/Utils/Element.elm
Labels: bug

#67 WMS-412 | Sync Badges' colors with Figma
  showcase/src/Badges.elm
  src/UI/Badge.elm
  tests/Tests/UI/Badge.elm
Labels: design-sync

#65 POC | Generate Elm code from i18n's JSONs
  i18n.json
  i18n/English.json
  i18n/Spanish.json
  package.json
  showcase/src/Main.elm
  showcase/src/Tables/Stories.elm
  src/I18n/English.elm
  src/I18n/Spanish.elm
  src/I18n/Types.elm
  src/UI/Checkbox.elm
  src/UI/Internal/DateInput.elm
  src/UI/Internal/Dialog.elm
  src/UI/Internal/RenderConfig.elm
  src/UI/Internal/SideBar.elm
  src/UI/Internal/Tables/FiltersView.elm
  src/UI/ListView.elm
  src/UI/Paginator.elm
  src/UI/Radio.elm
  src/UI/RenderConfig.elm
  src/UI/Tables/Stateful.elm
  tests/Tests/UI/RenderConfig.elm
  tests/Tests/UI/TextField.elm
  tests/Tests/Utils/RenderConfig.elm
  yarn.lock
Labels: enhancement
