Repository PaackEng/paack-ui, pull requests merged in 2020-09, with the labels that each got.

#88 Fix different header size from Figma
  src/UI/Internal/Tables/FiltersView.elm
Labels: hotfix

#89 Fix different header size from Figma ++
  src/UI/Internal/Tables/FiltersView.elm
Labels: hotfix

#92 WMS-529 | Make ellipsizable-text conform to new api
  package.json
  src/UI/Internal/Text.elm
  yarn.lock
Labels: blocked by paack-ui-assets

#93 WMS-462 | Use analyse in tests & showcase (Part 2)
  elm.json
  tests/Tests/UI/Alert.elm
  tests/Tests/UI/Badge.elm
  tests/Tests/UI/Button.elm
  tests/Tests/UI/ListView.elm
  tests/Tests/UI/Tabs.elm
  tests/Tests/UI/TextField.elm
  tests/Tests/Utils/ExtraSelectors.elm
Labels: cleanup, enhancement

#94 WMS-535 | Percy Improvements
  cypress/integration/visual-regression.spec.js
  showcase/src/Alerts.elm
  showcase/src/Badges.elm
  showcase/src/Buttons/Stories.elm
  showcase/src/Sizes.elm
  showcase/src/TextField.elm
  src/UI/Checkbox.elm
Labels: bug

#97 Enhancement | Add "remove" icon
  showcase/src/Icons.elm
  src/UI/Icon.elm
Labels: enhancement

#98 WMS-Phase3 | Some fixes
  src/UI/Checkbox.elm
  src/UI/Internal/Dialog.elm
Labels: hotfix

#99 WMS-Phase3 | Badges fixes
  src/UI/Badge.elm
  src/UI/SummaryListItem.elm
Labels: bug

#102 Border-radius to Dialog; add ListVIew.withSelectStyle
  src/UI/Badge.elm
  src/UI/Internal/Basics.elm
  src/UI/Internal/Dialog.elm
  src/UI/ListView.elm
Labels: enhancement

#105 WMS-446 | Upgrade dependencies
  package-lock.json
  yarn.lock
Labels: hotfix

#107 WMS-589 | Make our login page comply to LastPass
  src/UI/TextField.elm
  src/UI/Utils/Element.elm
Labels: hotfix

#106 WMS-514 | Run Percy on a separate workflow
  .github/workflows/ci.yml
  .github/workflows/percy.yml
Labels: proposal

#108 WMS-589 | Make our login page comply to LastPass (apply to password too)
  src/UI/TextField.elm
  src/UI/Utils/Element.elm
Labels: hotfix

#109 WMS-587 | Fix inconsistencies between Figma's mobile spaces and current implementation
  src/UI/Button.elm
  src/UI/Internal/Button.elm
  src/UI/Internal/Nav/StackHeader.elm
  src/UI/Internal/NavigationContainer.elm
  src/UI/Internal/SideBar.elm
  src/UI/Layout/SplitSelectable.elm
  src/UI/ListView.elm
  src/UI/NavigationContainer.elm
Labels: design-sync
