Repository PaackEng/paack-ui, pull requests merged in 2021-09, with the labels that each got.

#294 DES-121 | Add labeled icons to buttons
  elm.json
  package.json
  showcase/src/Buttons/Stories.elm
  showcase/src/Sizes.elm
  src/UI/Button.elm
  src/UI/Internal/Button.elm
  yarn.lock
Labels: enhancement, design-sync

#296 Alerts and icons.
  elm.json
  showcase/src/Alerts.elm
  showcase/src/Icons.elm
  src/UI/Alert.elm
  src/UI/Icon.elm
  src/UI/Internal/Svg.elm
  src/UI/LoadingView.elm
Labels: enhancement

#302 LMO-862 | Finish polishing button with label and icon.
  package.json
  src/UI/Button.elm
  src/UI/Internal/Button.elm
  yarn.lock
Labels: design-sync

#304 UI.Document.modelUpdateWithoutPerform
  README.md
  elm.json
  src/UI/Document.elm
Labels: bug

#310 Update Badge.elm
  src/UI/Badge.elm
Labels: design-sync
